### Test 3: Create lead with contact and account information
POST {{url}}/api/v1/Lead/create
Content-Type: application/json
Authorization: Basic {{base64EncodedCredentials}}
X-Api-Key: {{apiUserToken}}

{
	"attributes": {
		"firstName": "Mike",
		"lastName": "Johnson",
		"emailAddress": "mike.johnson@innovate.co",
		"phoneNumber": "+1555123456",
		"title": "Product Manager",
		"website": "https://innovate.co",
		"description": "Enterprise lead with high potential",
		"status": "In Process",
		"source": "Cold Call",
		"optinDate": "2025-08-27 12:33:05",
        "utmContent": "OntarioGeneric",
		"utmMedium": "Online Form",
		"utmTerm": "",
		"optinSource": "ontario-childcare-architects",
		"optinChannels": [
			"Courriel"
		],
		"referredByContact": {
			"firstName": "Mike",
			"lastName": "Johnson",
			"emailAddress": "mike.johnson@innovate.co",
			"phoneNumber": "+1555123456",
			"title": "Product Manager",
			"account": {
				"name": "Innovate Co",
				"website": "https://innovate.co",
				"type": "Customer",
				"industry": "Technology"
			}
		},
		"referredByUser": {
			"emailAddress": "test@example.com"
		}
	}
}